---
apiVersion: v1
kind: Namespace
metadata:
  name: cert-manager-acme
---
apiVersion: v1
kind: Pod
metadata:
  name: acme2certifier
  namespace: cert-manager-acme
  labels:
    app: a2c
spec:
  hostname: acme-srv
  dnsPolicy: "None"
  automountServiceAccountToken: false
  dnsConfig:
    nameservers:
      - DNSMASQ_IP
  containers:
    - name: acme2certifier
      resources:
        requests:
          cpu: "250m"
          memory: "256Mi"
          storage: "1Gi"
          ephemeral-storage: "1Gi"
        limits:
          memory: "512Mi"
          storage: "1Gi"
          ephemeral-storage: "1Gi"
      image: grindsa/acme2certifier:devel
      imagePullPolicy: Never
      ports:
        - containerPort: 80
      volumeMounts:
        - mountPath: /var/www/acme2certifier/volume/
          name: a2c-volume
  volumes:
    - name: a2c-volume
      hostPath:
        path: /home/runner/work/acme2certifier/acme2certifier/data
        type: Directory
