name: Manual Installation test

on:
  push:
  pull_request:
    branches: [ devel ]
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 2 * * 6'

jobs:
  alma_nginx_wsgi:
    name: "alma_nginx_wsgi"
    runs-on: ubuntu-latest
    steps:
    - name: "checkout GIT"
      uses: actions/checkout@v2

    - name: "[ PREPARE ] get runner ip"
      run: |
        echo RUNNER_IP=$(ip addr show eth0 | grep -i "inet " | cut -d ' ' -f 6 | cut -d '/' -f 1) >> $GITHUB_ENV
        echo RUNNER_PATH=$(pwd | sed 's_/_\\/_g') >> $GITHUB_ENV
    - run: echo "runner IP is ${{ env.RUNNER_IP }}"

    - name: Branch name
      run: echo running on branch ${GITHUB_REF##*/}

    - name: "[ PREPARE ] environment"
      run: |
        docker network create acme

    - name: "[ PREPARE ] Almalinux instance"
      run: |
        cat examples/Docker/alamalinux-systemd/Dockerfile | docker build -t almalinux-systemd -f - . --no-cache
        docker run -d -id --privileged --network acme --name=acme_srv -v "$(pwd)/":/tmp/acme2certifier almalinux-systemd

    - name: "[ * ] uploading artificates"
      uses: actions/upload-artifact@v2
      if: ${{ failure() }}
      with:
        name: alma_nginx_wsgi.tar.gz
        path: ${{ github.workspace }}/artifact/upload/