# workflow to run the acme2certifier unittest suite

name: Markdown check

on:
  push:
  pull_request:
    branches: [ devel ]
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 2 * * 6'

jobs:
  markdown-link-check:
    # runs-on: ubuntu-latest
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@master
    #- uses: umbrelladocs/action-linkspector@v1
    #  with:
    #      github_token: ${{ secrets.github_token }}
    #      reporter: github-pr-review
    #      fail_level: any
    - uses: gaurav-nelson/github-action-markdown-link-check@v1
      with:
        use-quiet-mode: 'yes'
        use-verbose-mode: 'yes'
        config-file: '.github/mlc_config.json'
    - name: Lint changelog file root
      uses: avto-dev/markdown-lint@v1
      with:
        args: '*.md'
    - name: Lint changelog file root
      uses: avto-dev/markdown-lint@v1
      with:
        args: '*.md'
    - name: Lint changelog file docs
      uses: avto-dev/markdown-lint@v1
      with:
        args: './docs/*.md'
    - name: Lint changelog file docker
      uses: avto-dev/markdown-lint@v1
      with:
        args: './examples/Docker/*.md'
