# workflow to run the acme2certifier unittest suite

name: unittest

on:
  push:
    branches: [ devel ]
  pull_request:
    branches: [ devel ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: cp
      run: |
         cp examples/ca_handler/skeleton_ca_handler.py acme/ca_handler.py
         cp examples/acme_srv.cfg acme/
    - name: Python test
      run: |
        pytest
        # python setup.py test
